"""ExploitReproducer.t.sol generator (SPEC §9): a self-contained Foundry
test that redeploys the scenario, replays the minimized action sequence, and
asserts both attacker profit and protocol insolvency — so `forge test`
re-proves the finding from scratch, independent of Python.

Redeploys via test/Fixture.sol, whose constants are kept in sync with
scenarios/vulnerable.json (see both files' docstrings) — this generator is
only correct for exploits found against that scenario. A multi-scenario
Fixture is future work, not needed while there's exactly one scenario file.
"""

from __future__ import annotations

from engine.actions import Action, Candidate
from engine.deploy import Deployment
from engine.report import symbol_for

_TARGET_EXPR = {"AMM": "address(amm)", "LENDING": "address(lending)"}
_TOKEN_EXPR = {"USD": "address(usd)", "COL": "address(col)"}


def _action_literal(action: Action, deployment: Deployment) -> str:
    target_expr = _TARGET_EXPR.get(symbol_for(action.target, deployment), f'address(bytes20(hex"{action.target[2:]}"))')
    return (
        "AttackExecutor.Action({"
        f"actionType: uint8(AttackExecutor.ActionType.{action.action_type.name}), "
        f"target: {target_expr}, "
        f"amountRule: uint8(AttackExecutor.AmountRule.{action.amount_rule.name}), "
        f"amountParam: {action.amount_param}"
        "})"
    )


def generate_reproducer_sol(candidate: Candidate, deployment: Deployment, seed: int) -> str:
    """Returns Solidity source for a self-contained reproduction test."""
    flash_expr = _TOKEN_EXPR.get(
        symbol_for(candidate.flash_token, deployment), f'address(bytes20(hex"{candidate.flash_token[2:]}"))'
    )
    contract_name = f"ExploitReproducer_{seed}"
    actions_decl = "\n".join(
        f"        actions[{i}] = {_action_literal(a, deployment)};" for i, a in enumerate(candidate.actions)
    )

    return f"""\
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

// AUTO-GENERATED by engine/solgen.py — do not edit by hand; re-run the
// search/minimizer to regenerate. Redeploys the scenario from scratch and
// re-proves this finding independent of Python (SPEC §9).
import {{Fixture}} from "../Fixture.sol";
import {{AttackExecutor}} from "../../contracts/AttackExecutor.sol";

contract {contract_name} is Fixture {{
    function setUp() public {{
        setUpFixture();
    }}

    function test_exploit() public {{
        AttackExecutor.Action[] memory actions = new AttackExecutor.Action[]({len(candidate.actions)});
{actions_decl}

        vm.prank(attacker);
        executor.executeAttack({flash_expr}, {candidate.flash_amount}, actions);

        uint256 attackerUsd = usd.balanceOf(address(executor));
        uint256 attackerCol = col.balanceOf(address(executor));
        uint256 attackerLiquidUsdValue = attackerUsd + (attackerCol * REFERENCE_PRICE_USD) / 1e18;
        assertGt(attackerLiquidUsdValue, ATTACKER_INITIAL_CAPITAL_USD, "attacker should be profitable");

        uint256 debtUsd = lending.debtOf(address(executor));
        uint256 collateralUsdAtReference = (lending.collateralOf(address(executor)) * REFERENCE_PRICE_USD) / 1e18;
        assertGt(debtUsd, collateralUsdAtReference, "protocol should be left with bad debt");
    }}
}}
"""
